creating new DedUpSite
DARPA-CRITICALMAAS/ta2-minmod-editor pull request #39
Opened 2024-12-12 03:12 UTC by NithyashreeGS30

2024-12-16 22:36 UTC, binh-vu requested changes

2024-12-16 22:36 UTC, binh-vu commented on www/src/models/mineralSite/MineralSite.ts
> +    super({ ...rest });
change to just super(rest);

2024-12-16 22:36 UTC, binh-vu commented on www/src/models/units/UnitStore.tsx
> +    id: string;
change the typing from string to `IRI` in `typing.ts`

2024-12-16 22:36 UTC, binh-vu commented on www/src/models/units/UnitStore.tsx
> +    public getByURI(uri: string): Unit | undefined {
change string to `IRI`

2024-12-16 22:36 UTC, binh-vu commented on www/src/models/units/UnitStore.tsx
> +        return { items: resp.data, total: resp.total };
bug, use `total: resp.data.length` instead -- please update other stores country, state, commodity, and deposit type for me.

2024-12-16 22:36 UTC, binh-vu commented on www/src/pages/home/DedupMineralSiteTable.tsx
> +        ]
please rebase, old code

2024-12-16 22:36 UTC, binh-vu commented on www/src/pages/home/NewMineralSite/NewMineralSiteModal.tsx
> +        });
don't do it here

2024-12-16 22:36 UTC, binh-vu commented on www/src/pages/home/NewMineralSite/NewMineralSiteModal.tsx
> +            const createdBy = `https://minmod.isi.edu/users/u/${currentUser}`;
we do not hard code createdBy any more

2024-12-16 22:36 UTC, binh-vu commented on www/src/pages/home/NewMineralSite/NewMineralSiteModal.tsx
> +                mineralInventory: [],
populate the mineralInventory field with data

2024-12-16 22:36 UTC, binh-vu commented on www/src/pages/home/NewMineralSite/NewMineralSiteModal.tsx
> +                mineralInventory: [],
gradeTonnage is temporary and will be discard if there is no mineral inventory

2024-12-17 00:12 UTC, binh-vu commented
rank default is U, type default is unspecified.

2024-12-17 00:24 UTC, binh-vu commented on www/src/pages/home/NewMineralSite/NewMineralSiteModal.tsx
> +                        source: values.stateorprovince,
incorrect source, use user url

2024-12-25 12:18 UTC, NithyashreeGS30 commented on www/src/pages/home/NewMineralSite/NewMineralSiteModal.tsx
> +        });
where do you want me to move it to ?

2024-12-27 07:44 UTC, closed without merging